name: Android CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME_GITHUB: ${{ secrets.GITHUB_USERNAME }}
      TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ProtoHax-build-${{ github.sha }}
        path: ./app/build/outputs/apk/release/app-release.apk
    - name: Download APK from build
      uses: actions/download-artifact@v1
      with:
        name: apk
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.event.repository.name }}  ${{ steps.branch-name.outputs.current_branch }} v${{ github.run_number }}.${{ github.run_attempt }}
    - name: Upload Release APK
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: apk/app-release.apk
        asset_name: ${{ github.event.repository.name }}.apk
        asset_content_type: application/zip
